### ISSUE TITLE
ValueError: Unknown layer type: ThnnConv2D

### ISSUE THREAD

**Issue by georgeokelly** [starimeL/PytorchConverter#12]
Hi, I got this error when I tried the run.py 
```
FaceBoxes
Saving default weight initialization...
Converting...
Traceback (most recent call last):
  File "run.py", line 101, in <module>
    text_net, binary_weights = ConvertModel_ncnn(pytorch_net, InputShape, softmax=False)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 327, in ConvertModel_ncnn
    DFS(out.grad_fn)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 85, in DFS
    child_name = DFS(u[0])
  [Previous line repeated 22 more times]
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertModel.py", line 160, in DFS
    layer = convert('', layer_type_name, func)
  File "/home/georgeokelly/convertor/PytorchConverter/code/ConvertLayer_ncnn.py", line 469, in convert_ncnn
    typename, converter.keys()))
ValueError: Unknown layer type: ThnnConv2D, known types: dict_keys(['data', 'Addmm', 'Threshold', 'ConvNd', 'MaxPool2d', 'AvgPool2d', 'Add', 'Cmax', 'BatchNorm', 'Concat', 'Dro
pout', 'UpsamplingBilinear2d', 'MulConstant', 'AddConstant', 'Softmax', 'Sigmoid', 'Tanh', 'ELU', 'LeakyReLU', 'PReLU', 'Slice', 'MultiCopy', 'Negate', 'Permute', 'View'])
```

**Comment by AnshanTJU** [comment]
Same error occured. 
Does anyone have a solution?

**Comment by starimeL** [comment]
It is because of Pytorch changed their namespace in recent updates. Please use the version 0.2.0 of Pytorch to convert models at present.
The newest 0.4.0 might be a stable version, the converter will support 0.4.0 soon:)

**Comment by zheshipinyinMc** [comment]
Same error occured.
Does anyone have a solution?

**Comment by Lvhhhh** [comment]
> It is because of Pytorch changed their namespace in recent updates. Please use the version 0.2.0 of Pytorch to convert models at present.
> The newest 0.4.0 might be a stable version, the converter will support 0.4.0 soon:)

can you offer me the 0.4.0 version？thanks
