### ISSUE TITLE
KeyError: 'unexpected key "epoch" in state_dict'

### ISSUE THREAD

**Issue by Coderx7** [starimeL/PytorchConverter#16]
Hi, Thank you very much for your great job. When I tried to run the script to convert a model from Pytorch to Caffe, I faced this error : 
```
(pytorch_env) hossein@hossein:/media/hossein/tmpstore/PytorchConverter-master/code$ python run.py 

Traceback (most recent call last):
  File "run.py", line 92, in <module>
    pytorch_net.load_state_dict(torch.load(model_path, map_location=lambda storage, loc: storage))
  File "/media/hossein/tmpstore/PytorchConverter-master/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 355, in load_state_dict
    .format(name))
KeyError: 'unexpected key "epoch" in state_dict'
```
How do I fix it? 
Thank you very much in advance

**Comment by Coderx7** [comment]
It would help alot newbies to pytorch like me if you could provide an example on how to use this script! where to change and what not!
My error is now : 
```
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    pytorch_net.load_state_dict(torch.load(model_path, map_location=lambda storage, loc: storage))
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for simplenetv1_imagenet_3p:
	Missing key(s) in state_dict: "features.0.weight", "features.0.bias", "features.1.weight", "features.1.bias", "features.1.running_mean", "features.1.running_var", "features.3.weight", "features.3.bias", "features.4.weight", "features.4.bias", "features.4.running_mean", "features.4.running_var", "features.6.weight", "features.6.bias", "features.7.weight", "features.7.bias", "features.7.running_mean", "features.7.running_var", "features.9.weight", "features.9.bias", "features.10.weight", "features.10.bias", "features.10.running_mean", "features.10.running_var", "features.13.weight", "features.13.bias", "features.14.weight", "features.14.bias", "features.14.running_mean", "features.14.running_var", "features.16.weight", "features.16.bias", "features.17.weight", "features.17.bias", "features.17.running_mean", "features.17.running_var", "features.19.weight", "features.19.bias", "features.20.weight", "features.20.bias", "features.20.running_mean", "features.20.running_var", "features.22.weight", "features.22.bias", "features.23.weight", "features.23.bias", "features.23.running_mean", "features.23.running_var", "features.25.weight", "features.25.bias", "features.26.weight", "features.26.bias", "features.26.running_mean", "features.26.running_var", "features.28.weight", "features.28.bias", "features.29.weight", "features.29.bias", "features.29.running_mean", "features.29.running_var", "features.32.weight", "features.32.bias", "features.33.weight", "features.33.bias", "features.33.running_mean", "features.33.running_var", "features.35.weight", "features.35.bias", "features.36.weight", "features.36.bias", "features.36.running_mean", "features.36.running_var", "features.39.weight", "features.39.bias", "features.40.weight", "features.40.bias", "features.40.running_mean", "features.40.running_var", "classifier.weight", "classifier.bias". 
	Unexpected key(s) in state_dict: "epoch", "arch", "state_dict", "best_prec1", "best_prec5", "optimizer". 
```
what should I do now?

**Comment by starimeL** [comment]
If the model is trained by your own. Try another model saving method:
net_for_saving = net.module if use_nn_DataParallel else net
torch.save(net_for_saving.state_dict(), path)

**Comment by xialeizhou** [comment]
> If the model is trained by your own. Try another model saving method:
> net_for_saving = net.module if use_nn_DataParallel else net
> torch.save(net_for_saving.state_dict(), path)

it's not work,  EOFError occurred

**Comment by yuemengyuan** [comment]
@xialeizhou Hello, I have encountered the same problem. Can you solve it? Can I get your help?
