### ISSUE TITLE
Unknown layer type: Expand

### ISSUE THREAD

**Issue by xuzijian** [starimeL/PytorchConverter#7]
Thanks for your nice conversion tools. However, I encountered such errors when I tried to convert my models:
```
Traceback (most recent call last):
  File "convert_my_net.py", line 51, in <module>
    text_net, binary_weights = ConvertModel_caffe(pytorch_net, InputShape, softmax=False)
  File "/data3/zjxu/CODE/pytorch-project/mobile_classification/PytorchConverter/code/ConvertModel.py", line 321, in ConvertModel_caffe
    DFS(out.grad_fn)
  File "/data3/zjxu/CODE/pytorch-project/mobile_classification/PytorchConverter/code/ConvertModel.py", line 83, in DFS
    child_name = DFS(u[0])
  File "/data3/zjxu/CODE/pytorch-project/mobile_classification/PytorchConverter/code/ConvertModel.py", line 83, in DFS
    child_name = DFS(u[0])
  File "/data3/zjxu/CODE/pytorch-project/mobile_classification/PytorchConverter/code/ConvertModel.py", line 161, in DFS
    layer = convert('', layer_type_name, func)
  File "/data3/zjxu/CODE/pytorch-project/mobile_classification/PytorchConverter/code/ConvertLayer_caffe.py", line 385, in convert_caffe
    typename, converter.keys()))
ValueError: Unknown layer type: Expand, known types: ['LeakyReLU', 'Index', 'BatchNorm', 'AddConstant', 'UpsamplingBilinear2d', 'Tanh', 'MulConstant', 'Dropout', 'PReLU', 'Add', 'MaxPool2d', 'AvgPool2d', 'Addmm', 'Softmax', 'View', 'Threshold', 'ConvNd', 'Cmax', 'data', 'Concat', 'ELU']
```

I'm a newbie of pytorch and don't know what does 'Expand' stands for. Could you help me solve such problem? Thanks in advance.

**Comment by elyor-anyvision** [comment]
I had also the same problem. Then, I downgraded pytorch 0.3.0 to 0.2.0, and it worked. Somehow, the current version is not compatible with 0.3.0. I tried resnet btw. Thanks.

**Comment by Elyorcv** [comment]
I also had the same problem. The, I downgraded pytorch 0.3.0 to 0.2.0, and it worked. Current version is not compatible with 0.3.0. I tried resnet. Thanks.

**Comment by starimeL** [comment]
@Elyorcv Thanks for pointing out! I guess I should make compatibility with 0.3.0 soon:)

**Comment by songyy137222** [comment]
@Elyorcv  how to downgraded pytorch 0.3.0 to 0.2.0,

**Comment by songyy137222** [comment]
@starimeL I also had the same problem.Do you solved it???

**Comment by starimeL** [comment]
You can download 0.2.0 anaconda or pip packages and re-install @songyy137222
